version: "3"
services:
  pudl-jupyterlab:
    image: catalystcoop/pudl-jupyter:latest
    volumes:
      - type: bind
        source: ${PUDL_DATA}
        target: /home/jovyan/shared
        read_only: true
        consistency: delegated
      - type: bind
        source: ${USER_DATA}
        target: /home/jovyan/user_data
        consistency: delegated
      - type: bind
        source: ./notebooks
        target: /home/jovyan/notebooks
        consistency: delegated
    environment:
      - API_KEY_EIA
    ports:
      - published: 48512
        target: 48512
    container_name: pudl_jupyter
    command: jupyter lab --ip 0.0.0.0 --port=48512 --no-browser
