version: "3"
services:
  pudl-jupyterlab:
    image: catalystcoop/pilot-hub:2021.02.12
    volumes:
      - type: bind
        source: ${PUDL_DATA}
        target: /home/jovyan/shared
        read_only: true
        consistency: delegated
      - type: bind
        source: ${USER_DATA}
        target: /home/jovyan/user_data
        consistency: delegated
    environment:
      - API_KEY_EIA
    ports:
      - published: 8888
        target: ${PUDL_JUPYTERLAB_PORT}
    container_name: pudl_jupyterlab
    command: jupyter lab --ip 0.0.0.0 --no-browser
