name: pudl
channels:
  - conda-forge
  - defaults
dependencies:
  - pip~=21.0
  - python~=3.8
  - setuptools_scm~=5.0.1

  # install_requires
  - addfips~=0.3.0
  - catalystcoop.dbfread~=3.0
  - coloredlogs~=15.0
  - contextily~=1.0
  - datapackage~=1.11
  - fsspec~=0.8.5
  - gcsfs~=0.7.1
  - geopandas~=0.8.1
  - goodtables-pandas-py~=0.2.0
  - google-cloud-storage~=1.35.0
  - matplotlib~=3.0
  - nbgitpuller~=0.9
  - networkx~=2.2
  - numpy~=1.20
  - pandas~=1.2
  - pyarrow~=3.0
  - pyyaml~=5.0
  - python-snappy~=0.6.0
  - scikit-learn~=0.24
  - scipy~=1.6
  - seaborn~=0.11.1
  - sqlalchemy~=1.3
  - tableschema~=1.12
  - tableschema-sql~=1.3
  - timezonefinder~=5.0
  - tqdm~=4.0
  - xlsxwriter~=1.3

  # user environment
  - dask~=2020.12
  - dask-labextension~=5.0
  - jupyter-resource-usage~=0.5.0
  - jupyterlab~=3.0
  - pygeos~=0.8.0
  - pysal~=2.1.0
  - python-graphviz~=0.16.0

  - pip:
    - git+https://github.com/catalyst-cooperative/pudl.git@jupyterhub-beta
    - recordlinkage~=0.14.0
    - fredapi~=0.4.3
    - jupyter-offlinenotebook~=0.2
