name: pudl
channels:
  - conda-forge
  - defaults
  - intake
dependencies:
  - pip~=21.0
  - python>=3.8,<3.9
  - python-snappy~=0.6.0 # Ensures snappy-dev library is installed w/o apt

  # user environment
  - dask~=2021.2
  - dask-labextension~=5.0
  - jupyterlab~=3.0
  - jupyter-resource-usage~=0.5.0
  - nbgitpuller~=0.9
  - python-graphviz~=0.16.0

  - pip:
    - git+https://github.com/catalyst-cooperative/pudl.git@jupyterhub-beta
    - jupyter-offlinenotebook~=0.2
